services: 
    - mysql:5.5

variables:
  MYSQL_ROOT_PASSWORD: sydns
  MYSQL_DATABASE: powerdns
  MYSQL_USER: sydns
  MYSQL_PASSWORD: sydns
    
before_script:
  - git submodule update --init
  - virtualenv -p `which python3` env
  - source env/bin/activate
  - make install_dev
  - mv sample/configuration.py sydns/configuration.py
  - python manage.py migrate

stages:
  - test

run-test:
  stage: test
  script:
    - make test
