services: 
    - mysql:5.5

variables:
  MYSQL_ROOT_PASSWORD: sydns
  MYSQL_DATABASE: powerdns
  MYSQL_USER: sydns
  MYSQL_PASSWORD: sydns
    
before_script:
  - make install
  - mv sample/configuration.py sydns/sydns/configuration.py
  - python3 sydns/manage.py migrate

stages:
  - test

run-test:
  stage: test
  script:
    - make test
