services: 
    - mysql:5.5

variables:
  MYSQL_ROOT_PASSWORD: sydns
  MYSQL_DATABASE: powerdns
  MYSQL_USER: sydns
  MYSQL_PASSWORD: sydns
    
before_script:
  - mysql -hmysql -usydns -psydns powerdns < sample/powerdns_schema.sql
  - mysql -hmysql -usydns -psydns powerdns < sample/patched_database_schema.sql
  - make install
  - mv sample/settings.py sydns/sydns/settings.py

stages:
  - test

run-test:
  stage: test
  script:
    - make test
