services:
    - mysql:5.5

variables:
  MYSQL_ROOT_PASSWORD: powerdns
  MYSQL_DATABASE: powerdns
  MYSQL_USER: powerdns
  MYSQL_PASSWORD: powerdns

before_script:
  - export PIP_CACHE_DIR='pip-cache'
  - export DJANGO_SETTINGS_MODULE=powerdns.settings_ci
  - git submodule update --init
  - virtualenv -p `which python3` env
  - source env/bin/activate
  - make install_dev

stages:
  - test

run-test:
  stage: test
  script:
    - make test

cache:
  paths:
    - pip-cache
