version: '2'
services:
  db:
    image: mysql:5.5
    hostname: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sydns
      MYSQL_DATABASE: powerdns
      MYSQL_USER: sydns
      MYSQL_PASSWORD: sydns
