version: '2'
services:
  db:
    image: mysql:5.5
    hostname: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: poweradmin
      MYSQL_DATABASE: poweradmin
      MYSQL_USER: poweradmin
      MYSQL_PASSWORD: poweradmin
